---
title: C6312
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
ms.openlocfilehash: cf9e04a76e174eca084d4b6f4c83ab3f504560f9
ms.sourcegitcommit: 7bea0420d0e476287641edeb33a9d5689a98cb98
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 02/17/2020
ms.locfileid: "77419818"
---
# <a name="c6312"></a>C6312

> Warning C6312: możliwa nieskończona pętla: Użycie stałej EXCEPTION_CONTINUE_EXECUTION w wyrażeniu filtru wyjątków try-except

To ostrzeżenie wskazuje na użycie stałej `EXCEPTION_CONTINUE_EXECUTION` (lub inną stałą, która jest szacowana do-1) w wyrażeniu filtru programu obsługi wyjątków strukturalnych. Użycie stałej wartości `EXCEPTION_CONTINUE_EXECUTION` może prowadzić do nieskończonej pętli. Na przykład, jeśli wyjątek został zgłoszony przez sprzęt, instrukcja, która spowodowała wyjątek, zostanie uruchomiona ponownie. Jeśli adres, który spowodował wyjątek, jest nadal zły, inny wyjątek wystąpi i będzie obsługiwany w ten sam sposób. Powoduje to nieskończoną pętlę.

Jawne wywołanie `RaiseException` nie spowoduje bezpośredniej pętli nieskończonej, ale będzie kontynuować wykonywanie kodu w bloku chronionym. Może to być nieoczekiwane i może prowadzić do nieskończonej pętli, jeśli użyto `RaiseException`, aby uniknąć odwołującego się do nieprawidłowego wskaźnika.

Zwykle `EXCEPTION_CONTINUE_EXECUTION` powinny być zwracane tylko przez funkcję o nazwie w wyrażeniu filtru, która ma szansę na rozwiązanie wskaźnika, który spowodował wyjątek lub pamięć źródłową.

## <a name="example"></a>Przykład

Poniższy kod generuje to ostrzeżenie:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (EXCEPTION_CONTINUE_EXECUTION)
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler
    //  block of the structured exception handler is not executed.
  {
    puts("This block is never executed");
  }
}
```

Aby poprawić to ostrzeżenie, należy użyć następującego kodu:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Error Occurred");
  }
}
```
