---
description: 'Dowiedz się więcej na temat: C6312'
title: C6312
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
ms.openlocfilehash: e53a4701df3f65c2365bee0fe8492b044643801f
ms.sourcegitcommit: d6af41e42699628c3e2e6063ec7b03931a49a098
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 12/11/2020
ms.locfileid: "97321072"
---
# <a name="c6312"></a>C6312

> Warning C6312: możliwa nieskończona pętla: Użycie stałej EXCEPTION_CONTINUE_EXECUTION w wyrażeniu filtru wyjątków try-except

To ostrzeżenie wskazuje na użycie stałej `EXCEPTION_CONTINUE_EXECUTION` (lub innej stałej, której wynikiem jest wartość-1) w wyrażeniu filtru programu obsługi wyjątków strukturalnych. Użycie stałej wartości `EXCEPTION_CONTINUE_EXECUTION` może prowadzić do nieskończonej pętli. Na przykład, jeśli wyjątek został zgłoszony przez sprzęt, instrukcja, która spowodowała wyjątek, zostanie uruchomiona ponownie. Jeśli adres, który spowodował wyjątek, jest nadal zły, inny wyjątek wystąpi i będzie obsługiwany w ten sam sposób. Powoduje to nieskończoną pętlę.

Jawne wywołanie nie powoduje `RaiseException` bezpośredniej pętli nieskończonej, ale będzie kontynuować wykonywanie kodu w bloku chronionym. Może to być nieoczekiwane i może prowadzić do nieskończonej pętli, jeśli `RaiseException` została użyta, aby uniknąć usunięcia odwołania do nieprawidłowego wskaźnika.

Zwykle `EXCEPTION_CONTINUE_EXECUTION` powinna być zwracana tylko przez funkcję o nazwie w wyrażeniu filtru, która ma szansę naprawić wskaźnik, który spowodował wyjątek lub pamięć źródłową.

## <a name="example"></a>Przykład

Poniższy kod generuje to ostrzeżenie:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (EXCEPTION_CONTINUE_EXECUTION)
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler
    //  block of the structured exception handler is not executed.
  {
    puts("This block is never executed");
  }
}
```

Aby poprawić to ostrzeżenie, należy użyć następującego kodu:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Error Occurred");
  }
}
```
